### ISSUE TITLE
Provide a real C# API

### ISSUE THREAD

**Issue by levibotelho** [mailin-api/mailin-api-csharp#1]
V2 of the API works but is clearly copy pasted from Java or another language. A few issues come to mind straight away:
- The API doesn't follow standard C# naming conventions
- `dynamic` everywhere reduces performance with no tangible benefit (should return POCOs)
- Methods could easily take POCOs instead of dictionaries for static typing
- Documentation comments don't follow the triple-slash XML standard so don't show up in Visual Studio as they should
- There's no async-await
- There's no interface (thinking of unit testing here)
- There's no NuGet package

I copy-pasted V2 into a project of mine and fixed the naming, added async-await, extracted an interface, and return `JObject`s instead of `dynamic` everywhere. It's far from perfect but if you were interested in doing a real C# API for a V3 I'd be happy to pass the file along in a PR such that it could be improved upon by a member of your team.

The sendinblue service itself is fantastic by the way -- I'm really happy with it so far. It would be great if it had a real C# API to complement it.

**Comment by erikbartlow** [comment]
I would be very interested in your "more standard" version.  Care to share?

**Comment by levibotelho** [comment]
Sorry for the late reply, was on holiday. See my comment on the PR.

**Comment by erikbartlow** [comment]
I will take a look at a pull.  Thanks.

**Comment by levibotelho** [comment]
Cool let me know if I can lend a hand.

**Comment by JeePeeTee** [comment]
Have 'upgraded' some parts already and would like to lend a hand too...

**Comment by TheRealGangstaCoder** [comment]
whoa they call this an API???

moving along to another provider, I dont have the time or the patience in my project to onboard a service that provide such a poor development experience

**Comment by balivo** [comment]
I started today, check: https://www.nuget.org/packages/Balivo.SendInBlue

Just send transactional email supported, but I'll update in a fews days fo full support.

Repo: https://github.com/balivo/sendinblue-sdk

**Comment by MichalGrzegorzak** [comment]
@TheRealGangstaCoder just curious which provider would you recommend?

**Comment by TheRealGangstaCoder** [comment]
@MichalGrzegorzak I ended up putting up with it, because while the api is terrible, once its built, i dont worry too much about it, and the actual product and service offering is quite good

**Comment by JakubHolovsky** [comment]
+1 for officialy mainained nuget package

**Comment by ekta-slit** [comment]
As part of the sendinblue API version 2 deprecation plan this repository is no longer supported. Please refer to its updated version 3: https://github.com/sendinblue/APIv3-csharp-library
