### ISSUE TITLE
Upload library to NuGet

### ISSUE THREAD

**Issue by movsesiv** [mailin-api/mailin-api-csharp#3]

**Comment by erikbartlow** [comment]
A nuget package would be awesome.

**Comment by neuhoffm** [comment]
agreed!

**Comment by levibotelho** [comment]
Mentioned this on https://github.com/mailin-api/mailin-api-csharp/pull/2.

**Comment by danocaFR** [comment]
Yes we can't use this library in a .NET Core :
".NET Core projects only support referencing .NET framework assemblies in this release. To reference other assemblies, they need to be included in a NuGet package and reference that package.".

If you want to create your own Nuget package, use this tutorial :
https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package

**Comment by dogansalman** [comment]
agreed!

**Comment by huytnd** [comment]
Any update?

**Comment by albertliang** [comment]
any chance of this happening soon?

**Comment by bradley-varol** [comment]
bump! SendinBlue looks like a great SendGrid alternative but I can't use it without a NuGet package!

**Comment by scurk1415** [comment]
I would also like to see this happen.

**Comment by manuel-guilbault** [comment]
+1

**Comment by ekta-slit** [comment]
Hello,

Thanks for showing your kind patience.
We have launched [RESTful API V3.0](https://developers.sendinblue.com/) and by the first quarter of 2018 we will have it in NuGet package.

Regards
SendinBlue Team
